### ISSUE TITLE
Muxer fails with FileNotFoundError

### ISSUE THREAD

**Issue by vmware-lol** [stefanodvx/flixcrack#14]
First, thanks for your hard work, this _almost_ works perfectly for me, until it gets to the Muxing step, and then it fails, here's the traceback:

```
Muxing all tracks...
Traceback (most recent call last):
  File "C:\widevine\flixcrack\main.py", line 27, in <module>
    asyncio.run(main())
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\widevine\flixcrack\main.py", line 19, in main
    await client.download(item["viewable_id"],
  File "C:\widevine\flixcrack\lib\site-packages\flixcrack\netflix.py", line 272, in download
    file_data = await muxer.run()
  File "C:\widevine\flixcrack\lib\site-packages\flixcrack\muxer.py", line 94, in run
    proc = await asyncio.create_subprocess_exec(
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 394, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 890, in _start
    self._proc = windows_utils.Popen(
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Process finished with exit code 1
```

I'm then left with the properly decrypted audio and video files, although they are in separate files. I'm sure I could use a different program to combine them, but just thought you should know that this step seems to be failing.

**Comment by vmware-lol** [comment]
It turns out mkvtoolnix wasn't correctly added to my PATH. Reboot fixed it, script is working perfectly 👌
